[workspace]
members = [
    "syscare-abi",
    "syscare-common",
    "syscare",
    "syscare-build",
    "syscared",
    "upatch-build",
]

[profile.release]
opt-level = 's'
debug = true
rpath = false
debug-assertions = false
overflow-checks = false
