[workspace]
members = [
    "syscare-abi",
    "syscare-common",
    "syscare",
    "syscare-build",
    "syscared",
    "upatch-build",
    "upatch-helper"
]

[profile.release]
opt-level = 3
debug = true
rpath = false
