include(GNUInstallDirs)

# Set install directories
set(SYSCARE_INSTALL_BINARY_DIR  "${CMAKE_INSTALL_FULL_BINDIR}")
set(SYSCARE_INSTALL_LIBEXEC_DIR "${CMAKE_INSTALL_FULL_LIBEXECDIR}/syscare")
set(SYSCARE_INSTALL_SERVICE_DIR "${CMAKE_INSTALL_PREFIX}/lib/systemd/system")
